---
title: "DESeq2 DEG Analysis"
# author: "Vishal Koparde, Ph.D."
output:
  html_document:
    toc: true
    toc_float: true
params:
  rawcountsmatrix: "/Volumes/Wolin/mESC_slam_analysis/find_mutation_101521/rsem/rsem.raw_counts_matrix.tsv"
  coldata: "/Volumes/Wolin/mESC_slam_analysis/find_mutation_101521/rsem/rsem.raw_counts_matrix.tsv.colData" # tab delimited file with header and 2 columns: sample_name, condition; samples with sample_name must exists in the raw counts matrix
  condition1: "KO"
  condition2: "WT" # contrasts is condition1 vs condition2 ... pay attention to the order of conditions
  indexcols: "gene_id,gene_name" # comma separated list of indexing columns eg. gene_id,gene_name
  cpm_cutoff: 1
  degoutdir: "/Volumes/Wolin/mESC_slam_analysis/find_mutation_101521/rsem/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library("DESeq2"))
suppressPackageStartupMessages(library("edgeR"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("DT"))
suppressPackageStartupMessages(library("pander"))
suppressPackageStartupMessages(library("plotly"))
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("ggfortify"))
suppressPackageStartupMessages(library("ggrepel"))
suppressPackageStartupMessages(library("vsn"))
suppressPackageStartupMessages(library("EnhancedVolcano"))
```

```{r read_inputs, include=FALSE}
debug=0
if (debug==1){
  rawcountsmatrix="/Users/kopardevn/Documents/Projects/rbl4/find_mutations_101521/DEGs/KO_vs_WT.0021.counts.tsv"
  coldata="/Users/kopardevn/Documents/Projects/rbl4/find_mutations_101521/DEGs/KO_vs_WT.0021.coldata.tsv" 
  condition1="KO"
  condition2="WT"
  indexcols=unlist(strsplit("gene_id,gene_name",",")) # comma separated list of indexing columns eg. gene_id,gene_name
  cpm_cutoff=1
  degoutdir="/Users/kopardevn/Documents/Projects/rbl4/find_mutations_101521/DEGs"
} else {
  rawcountsmatrix=params$rawcountsmatrix
  coldata=params$coldata
  indexcols=unlist(strsplit(params$indexcols,","))
  if (length(params$excludecols)==0){
   excludecols=c()
  } else {
   excludecols=unlist(strsplit(params$excludecols,","))
  }
  condition1=params$condition1
  condition2=params$condition2
  cpm_cutoff=params$cpm_cutoff
  degoutdir=params$degoutdir
}

# read sampleinfo
as.data.frame(read.csv(coldata,header = TRUE,sep="\t")) %>%
  dplyr::select(c("sample_name","condition")) -> cdata
  # column_to_rownames(.,var="sample_name") -> cdata
# change hyphen to underscore in conditions
cdata$condition = as.factor(gsub("-","_",cdata$condition))
filtercols=c(indexcols,cdata$sample_name)

# read in raw counts
d=read.csv(rawcountsmatrix,header=TRUE,sep="\t",check.names = FALSE)

# remove excludecols, concate includecols into a single column and use it as index
d %>% dplyr::select(all_of(filtercols)) %>%
  unite("geneID",all_of(indexcols),sep="##",remove=TRUE) %>%
  column_to_rownames(.,var="geneID") -> d
e=round(d,0)

col_rows=data.frame("Raw",ncol(e),nrow(e))
colnames(col_rows)=c("CountMatrix","Ncolumns","Nrows")
keep_columns=(cdata$condition==condition1 | cdata$condition==condition2)
e=e[,keep_columns]
cpm_e=cpm(e)
remove_rows=(rowSums(cpm_e<cpm_cutoff)==ncol(e))
e=e[!remove_rows,]

col_rows[nrow(col_rows)+1,]=c("Filtered",ncol(e),nrow(e))

#create sampleinfo
sampleinfo=cdata[keep_columns,]
rownames(sampleinfo)=c()
sampleinfo$condition <- droplevels(sampleinfo$condition)
sampleinfo$condition <- relevel(sampleinfo$condition, ref = condition2)
sampleinfo$library_size <- colSums(e)/1e6
```
## Filtering raw data

Input raw count matrix is filtered for:

* samples in `r condition1` and `r condition2`
* lowly expressed genes (cpm<`r cpm_cutoff`) in all `r ncol(e)` samples are filtered out

```{r filtered_table, echo=FALSE, include=TRUE}
# DT::datatable(col_rows,
#               rownames = FALSE,
#               options = list(columnDefs = list(list(className = 'dt-center', targets = 0:(ncol(col_rows)-1)))))
# knitr::kable( col_rows )
pander(col_rows,style="rmarkdown")
```

Samples retained for downstream analysis are:

```{r samples_table, echo=FALSE, include=TRUE}
pander(sampleinfo,style="rmarkdown")
```

## Library Size
```{r libsize, echo=FALSE, include=TRUE}
p <- ggplot(sampleinfo,aes(sample_name,library_size,fill=condition))+geom_bar(stat="identity",aes(col=condition))
p <- p + ylab("library_size_in_millions") + theme_light()
print(p)
```

```{r dds,echo=FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide'}
dds <- DESeqDataSetFromMatrix(countData = as.matrix(e),
                                colData = sampleinfo[,c("sample_name","condition")],
                                design = ~ condition)
```

## Calculating size factors

```{r sizeFactors,echo=FALSE}
dds <- estimateSizeFactors( dds )
pander(as.data.frame(sizeFactors(dds)) %>% rownames_to_column(var="sample"))
# plot(sizeFactors(dds), colSums(counts(dds)))
# abline(lm(colSums(counts(dds)) ~ sizeFactors(dds) + 0))
x=data.frame(sf=sizeFactors(dds),cs=colSums(counts(dds)))
ggplot(x,aes(x=sf,y=cs,label=rownames(x)))+geom_point(aes(col=as.factor(sampleinfo$condition)))+geom_text_repel()+theme_light()+ theme(legend.title = element_blank()) -> p
reg=lm(colSums(counts(dds)) ~ sizeFactors(dds) + 0)
p <- p + geom_abline(intercept = 0, slope=reg$coefficients[[1]], color="green", size=2, linetype="dashed")
p <- p + xlab("SizeFactors") + ylab("ColSums")
print(p)
```

```{r deseq2,echo=FALSE,include=FALSE}
dds <- DESeq(dds)
# deg results
res <- results(dds)
as.data.frame(res) %>% drop_na() %>% arrange(padj) %>% rownames_to_column(var="gene") -> res_df
res_df <- separate(res_df,col="gene",into=c("gene_id","gene_name"),sep="##")
log2FC2FC<-function(log2FC){
  if (log2FC>0){
    FC=2^log2FC
  } else {
    FC=-1/2^log2FC
  }
  return(FC)
}
res_df$FoldChange=lapply(res_df$log2FoldChange,log2FC2FC)
colnames(res_df)=c("gene_id","gene_name","baseMean",	"log2FoldChange",	"lfcSE",	"stat",	"pvalue",	"FDR","FoldChange")
res_df=res_df[,c("gene_id","gene_name","log2FoldChange","FDR","baseMean","lfcSE","stat","pvalue","FoldChange")]
contrast=paste(condition1,"vs",condition2,sep="_")
degoutfn=paste("DEG",contrast,"tsv",sep=".")
degoutfile=paste(degoutdir,degoutfn,sep="/")
res_df_out <- apply(res_df,2,as.character)
write.table(res_df_out,file=degoutfile,row.names = FALSE,col.names = TRUE,sep="\t",quote = FALSE)

# # vst
# vstd <- vst(dds)
# assayvstd = as.data.frame(assay(vstd))
# rlog for PCA
rld <- rlog(dds)
assayrld = as.data.frame(assay(rld))
assayrld$row_variance = rowVars(as.matrix(assayrld))
assayrld = arrange(assayrld,desc(row_variance)) 
zero_variance_rows=assayrld$row_variance<1e-5
assayrld$row_variance = NULL
assayrld = assayrld[!zero_variance_rows,]
assayrld = assayrld[1:500,]
pca=prcomp(t(assayrld),scale. = T)
m.pc1 = round(pca$sdev[1]^2/sum(pca$sdev^2)*100,2)
m.pc2 = round(pca$sdev[2]^2/sum(pca$sdev^2)*100,2)
m.pc3 = round(pca$sdev[3]^2/sum(pca$sdev^2)*100,2)
```

## PCA

```{r plotpca, echo=FALSE}
p <- ggplot2::autoplot(pca,label=T,repel = TRUE,label.size = 3,label.repel=T,colour=as.factor(as.numeric(sampleinfo$condition)))+theme_light()+ggtitle("PCA with top 500 genes")
print(p)
```


## MAPlot

```{r ma, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE,results='hide'}
p<-DESeq2::plotMA(dds)
print(p)
```


## DEG list

```{r degstats,echo=FALSE,include=TRUE,warning=FALSE,message=FALSE,error=FALSE}
regulation_results=data.frame("Up",
                              sum(res_df$FDR<0.05 & res_df$log2FoldChange > 1),
                              paste(head(res_df[(res_df$FDR<0.05 & res_df$log2FoldChange > 1),]$gene_name,5),collapse=", "))
colnames(regulation_results)=c("Regulation","Number of Genes","Top5")
regulation_results[nrow(regulation_results)+1,]=c("Down",
                                                  sum(res_df$FDR<0.05 & res_df$log2FoldChange < -1),
                                                  paste(head(res_df[(res_df$FDR<0.05 & res_df$log2FoldChange < -1),]$gene_name,5),collapse=", "))
pander(regulation_results,style="rmarkdown")
```

```{r degtable,echo=FALSE,include=TRUE,warning=FALSE,message=FALSE,error=FALSE}

display_df=res_df[,c("gene_id","gene_name","log2FoldChange","FoldChange","FDR")]

DT::datatable(display_df,options = list(pageLength = 10)) %>% 
  formatRound(columns=c("log2FoldChange","FoldChange"), digits=2) %>% 
  formatSignif(columns = c('FDR'), digits = 3)
```


## VolcanoPlot

```{r volcano,echo=FALSE,include=TRUE,fig.dim = c(12, 5),warning=FALSE,message=FALSE,error=FALSE,}
p <-  EnhancedVolcano::EnhancedVolcano(res_df, 
                lab = res_df$gene_name,
                x = "log2FoldChange", 
                y = "FDR", 
                ylab = bquote(~-Log[10]~FDR),
                FCcutoff = 1, 
                xlim=c(min(res_df$log2FoldChange)-1,max(res_df$log2FoldChange)+1),
                ylim= c(0, max(-log10(res_df$FDR), na.rm=TRUE) + 1),
                pCutoff = 0.05,
                legendPosition = 'top',
                pointSize = 0.8,
                labSize = 4,
                legendLabSize = 8,
                legendIconSize = 2,
                legendLabels = c("NS","log2FC > |1|","FDR < 0.05","significant (FDR < 0.05) & log2FC > |1|"),
                title="",titleLabSize=0,
                subtitle = "",subtitleLabSize = 1,
                caption = "",captionLabSize=0)
print(p)
```